### ISSUE TITLE
Asociar nicks a usuarios de telegram

### ISSUE THREAD

**Issue by itorres** [pandacrew-net/diosteama#5]
- [ ] Añadir comando `!soy` para que la gente pueda asociar su usuario de telegram a su nick de IRC.
- [ ] Añadir `!es` para administradores.

Esto requerirá una nueva tabla, lo que puede permitir más adelante un sistema de registro con diferentes niveles de acceso.

**Comment by wiredrat** [comment]
Lo tienes en el PR  #18
